apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_SERVER: postgresql.{{ .Release.Name }}.svc.cluster.local
  POSTGRES_USER: {{ .Values.postgresql.user }}
  POSTGRES_DB: {{ .Values.postgresql.db }}
  SEND_EMAIL: {{ .Values.email.send | quote}}
  SENDER_EMAIL: {{ .Values.email.sender }}
  SMTP_SERVER: {{ .Values.email.smtp_server}}
  RECEIVER: {{ .Values.email.receiver }}
  SMTP_PORT: {{ .Values.email.smtp_port | quote}}