apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgre
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}


