apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: 5000